### ISSUE TITLE
[QUESTION] Is it better to use bigger time frames?

### ISSUE THREAD

**Issue by shhhmel** [kentwar/binance_correlation_script#1]
@kentwar Is it better to use bigger time frames?
Currently to get corrsum you use this - `corrsum = new_day_corr[coin] + new_week_corr[coin] + new_two_week_corr[coin]`

Would it be better to also get  new_FOUR_week_corr[coin], new_EIGHT_week_corr[coin], new_TWELVE_week_corr[coin] and also add it to sum?
`corrsum = new_day_corr[coin] + new_week_corr[coin] + new_two_week_corr[coin] + new_four_week_corr[coin] + ...`

**Comment by kentwar** [comment]
Hey, apologies for slow response, Covid hit our family pretty hard!

So there's a couple of problems with the change. 

If we add the terms that you suggest the correlation sum will be heavily weighted by long term correlation values. The short term correlation will be much less significant. The issue therefore is that you may choose a coin that has historically tracked well but is now deviating heavily. In respect of your suggestion you could absolutely take a longer correlation term, but it should replace one of the other terms. The idea is to catch 24 hour volatility, mid term correlation and longer term trend. You should definitely not add more terms. 

The reason I took the intervals I did reflects my belief that crypto is like a sped up version of normal stocks with extra market manipulation (so I don't really care about the longer term historical data). Additionally, I wanted to be able to accept coins that had recently arrived on Binance without having to somehow account for the fact that there was no historical data.

Let me know how you get on with any changes you make.
